export const truckConfig = [
    {
        bayName: 'Passenger Side Bay 1',
        bayPosition: [2.5,-2.5,2],
        bayHeight: 4,
        bayWidth: 4,
        bayLength: 4,
        maxWeightinLBS : 100,
        //maxVolume: bayHeight * bayWidth * bayDepth,
    },
    {
        bayName: 'Passenger Side Bay 2',
        bayPosition: [-1.5,-2.5,2],
        bayHeight: 4,
        bayWidth: 4,
        bayLength: 4,
        maxWeightinLBS : 100,
        //maxVolume: bayHeight * bayWidth * bayDepth,
    },
    {
        bayName: 'Passenger Side Bay 3',
        bayPosition: [-5.5,-2.5,2],
        bayHeight: 4,
        bayWidth: 4,
        bayLength: 4,
        maxWeightinLBS : 100,
        //maxVolume: bayHeight * bayWidth * bayDepth,
    },
    {
        bayName: 'Passenger Side Bay 4',
        bayPosition: [-9,-2.5,2],
        bayHeight: 4,
        bayWidth: 4,
        bayLength: 3,
        maxWeightinLBS : 100,
        //maxVolume: bayHeight * bayWidth * bayDepth,
    },
    {
        bayName: 'Passenger Side Bay 5',
        bayPosition: [2.5,-6,2],
        bayHeight: 3,
        bayWidth: 4,
        bayLength: 4,
        maxWeightinLBS : 100,
        //maxVolume: bayHeight * bayWidth * bayDepth,
    },
    {
        bayName: 'Passenger Side Bay 6',
        bayPosition: [-1.5,-6,2],
        bayHeight: 3,
        bayWidth: 4,
        bayLength: 4,
        maxWeightinLBS : 100,
        //maxVolume: bayHeight * bayWidth * bayDepth,
    },
    {
        bayName: 'Passenger Side Bay 7',
        bayPosition: [-5.5,-6,2],
        bayHeight: 3,
        bayWidth: 4,
        bayLength: 4,
        maxWeightinLBS : 100,
        //maxVolume: bayHeight * bayWidth * bayDepth,
    },
    {
        bayName: 'Passenger Side Bay 8',
        bayPosition: [-9,-6,2],
        bayHeight: 3,
        bayWidth: 4,
        bayLength: 3,
        maxWeightinLBS : 100,
        //maxVolume: bayHeight * bayWidth * bayDepth,
    },
    {
        bayName: 'Driver Side Bay 1',
        bayPosition: [2.5,-2.5,-2.25],
        bayHeight: 4,
        bayWidth: 4,
        bayLength: 4,
        maxWeightinLBS : 100,
        //maxVolume: bayHeight * bayWidth * bayDepth,
    },
    {
        bayName: 'Driver Side Bay 2',
        bayPosition: [-1.5,-2.5,-2.25],
        bayHeight: 4,
        bayWidth: 4,
        bayLength: 4,
        maxWeightinLBS : 100,
        //maxVolume: bayHeight * bayWidth * bayDepth,
    },
    {
        bayName: 'Driver Side Bay 3',
        bayPosition: [-5.5,-2.5,-2.25],
        bayHeight: 4,
        bayWidth: 4,
        bayLength: 4,
        maxWeightinLBS : 100,
        //maxVolume: bayHeight * bayWidth * bayDepth,
    },
    {
        bayName: 'Driver Side Bay 4',
        bayPosition: [-9,-2.5,-2.25],
        bayHeight: 4,
        bayWidth: 4,
        bayLength: 3,
        maxWeightinLBS : 100,
        //maxVolume: bayHeight * bayWidth * bayDepth,
    },
    {
        bayName: 'Driver Side Bay 5',
        bayPosition: [2.5,-6,-2.25],
        bayHeight: 3,
        bayWidth: 4,
        bayLength: 4,
        maxWeightinLBS : 100,
        //maxVolume: bayHeight * bayWidth * bayDepth,
    },
    {
        bayName: 'Driver Side Bay 6',
        bayPosition: [-1.5,-6,-2.25],
        bayHeight: 3,
        bayWidth: 4,
        bayLength: 4,
        maxWeightinLBS : 100,
        //maxVolume: bayHeight * bayWidth * bayDepth,
    },
    {
        bayName: 'Driver Side Bay 7',
        bayPosition: [-5.5,-6,-2.25],
        bayHeight: 3,
        bayWidth: 4,
        bayLength: 4,
        maxWeightinLBS : 100,
        //maxVolume: bayHeight * bayWidth * bayDepth,
    },
    {
        bayName: 'Driver Side Bay 8',
        bayPosition: [-9,-6,-2.25],
        bayHeight: 3,
        bayWidth: 4,
        bayLength: 3,
        maxWeightinLBS : 100,
        //maxVolume: bayHeight * bayWidth * bayDepth,
    },
    
];

